### ISSUE TITLE
import from node_modules failing

### ISSUE THREAD

**Issue by borango** [observablehq/framework#1234]
According to https://observablehq.com/framework/imports#node-imports I should be able to import a ```lib``` which I had previously installed via ```npm i lib```. 

## Expected behaviour

1. cd into a Framework project
2. run ```npm i canvas-confetti```
3. run ```npm run dev```
4. add a doc page named ```confetti.md``` with following content  
<pre>
```js
import confetti from "canvas-confetti"
```

```js
Inputs.button("Throw confetti! 🎉", {reduce: () => confetti()})
```
</pre>
5. navigate to ```http://127.0.0.1:3000/confetti```
6. click button to throw confetti

## Observed behaviour

At step 5, I get 2 red lines of error messages:
```
TypeError: The specifier “canvas-confetti” was a bare specifier, but was not remapped to anything. Relative module specifiers must start with “./”, “../” or “/”.
RuntimeError: The specifier “canvas-confetti” was a bare specifier, but was not remapped to anything. Relative module specifiers must start with “./”, “../” or “/”.
```

I can verify the npm-installed lib both as an entry in package.json ```"canvas-confetti": "^1.9.2",```
and as a separate folder (with expected content) in ```node_modules/canvas-confetti/```

I tried deleting the cache and restarting the dev server. 

## Variant A
It works when I change the import in ```confetti.md``` to ```import confetti from "npm:canvas-confetti"``` (adding the ```npm:```).

## Variant B
I am observing the same failure for other libraries as well.

**Comment by Fil** [comment]
See #360; this is fixed in main (see https://github.com/observablehq/framework/commits/main/src/node.ts), but we haven't released a new version yet. A version badge is missing in the documentation.

**Comment by Fil** [comment]
(congratulations for getting issue #1234! 🔢 🎯)

**Comment by borango** [comment]
> (congratulations for getting issue #1234! 🔢 🎯)

Right, this was fun to see.

Thanks a lot for your quick response @Fil .

From my end I cannot confirm that this bug is solved, because I still get the same error. So far I am not building Framework from _main_ but installed it via `npm init @observablehq`.

Which release should I track so that I can `npm update` (or perform other action that is needed)?

Thank you for you help. Observable is awesome.

**Comment by Fil** [comment]
Releases are published on npm and documented [here](https://github.com/observablehq/framework/releases/). We hope to ship 1.6 next week or the week after. If you want to use the main branch, you can edit your project’s `package.json` and set:

>  "@observablehq/framework": "https://github.com/observablehq/framework#main",

then run `npm i`.

**Comment by mbostock** [comment]
I wouldn’t recommend installing from main as @Fil suggests (since that has other gotchas). I would just wait until we release this feature.

**Comment by borango** [comment]
Thanks Mike.

To bei fair: @Fil just reported that the fix is implemented in _main_ and I was asking out of curiousity. I appreciate the hint _how_ I could fetch from main if I were desperate enough. Perhaps next time ;-) This time I will wait for R 1.6

**Comment by mbostock** [comment]
From our perspective, the only issue was in the documentation, which as of #1236 now correctly notes that the feature is not yet released. That is why the feature is closed.

We won’t track an issue if a customer is trying to use a feature that’s not yet released. We don’t support features until they are released.

**Comment by borango** [comment]
You are my hero, @mbostock . I don't argue with you.
